version: '2.1'
services:
  beat:
    build: ${PWD}/.
    depends_on:
      - proxy_dep
    environment:
      - PULSAR_HOST=pulsar
      - PULSAR_PORT=6650
      - PULSAR_PORT_TLS=6651
      # Setup work environment
      - LIBBEAT_PATH=/go/src/github.com/elastic/beats/libbeat
    # env_file:
      # - ${PWD}/build/test.env
    volumes:
      - ${PWD}/..:/go/src/github.com/elastic/beats/
      # Used for docker integration tests:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /go/src/github.com/elastic/beats/libbeat
    # command: ${PWD}/filebeat-ouput-pulsar -e

  # This is a proxy used to block beats until all services are healthy.
  # See: https://github.com/docker/compose/issues/4369
  proxy_dep:
    image: busybox
    depends_on:
      # - pulsar: {condition: service_healthy}
      - pulsar
    # healthcheck:
    #   interval: 1s
    #   retries: 1200

  pulsar:
    build: ./pulsar
    # image: tuteng/pulsar-authentication-authorization:latest
    # expose:
    #   - 8080
    #   - 6650 
    #   - 6651
    #   - 8443
    # environment:
    #   - PULSAR_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    # command: >
    #   nohup bin/pulsar standalone >data/pulsar-standalone.log 2>&1 &
    volumes:
      - ${PWD}/data:/pulsar/data
  # elasticsearch:
  #   extends:
  #     file: ${ES_BEATS}/testing/environments/${TESTING_ENVIRONMENT}.yml
  #     service: elasticsearch

  # # This host name is static because of the certificate.
  # logstash:
  #   extends:
  #     file: ${ES_BEATS}/testing/environments/${TESTING_ENVIRONMENT}.yml
  #     service: logstash
  #   env_file:
  #     - ${PWD}/build/test.env
  #   depends_on:
  #     elasticsearch:
  #       condition: service_healthy

  # redis:
  #   build: ${ES_BEATS}/testing/environments/docker/redis

  # # This host name is static because of the certificate.
  # sredis: # stunnel proxy for redis
  #   build: ${ES_BEATS}/testing/environments/docker/sredis
  #   expose:
  #     - 6380
  #   depends_on:
  #     redis:
  #       condition: service_healthy
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #   env_file:
  #     - ${PWD}/build/test.env

  # kafka:
  #   build: ${ES_BEATS}/testing/environments/docker/kafka
  #   expose:
  #     - 9092
  #     - 2181
  #   environment:
  #     - ADVERTISED_HOST=kafka

  # kibana:
  #   extends:
  #     file: ${ES_BEATS}/testing/environments/${TESTING_ENVIRONMENT}.yml
  #     service: kibana
