name: elastic beat release by goreleaser

on:
  push:
    tags:
      - '*'

env:
  GOPRIVATE: github.com/streamnative

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.1.1
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.BEAT_ACCESS_TOKEN }}
          GOPATH: /home/runner/work/pulsar-beat-output/pulsar-beat-output/go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta for filebeat
        id: docker_meta_filebeat
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            streamnative/filebeat
          tag-sha: true

#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3

      - name: Build and push beat image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./filebeat/Dockerfile
          push: true
          tags: ${{ steps.docker_meta_filebeat.outputs.tags }}
          labels: ${{ steps.docker_meta_filebeat.outputs.labels }}